version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    command: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory-system